using Skclusive.Core.Component;

namespace Skclusive.Material.Menu
{
    public class MenuScript : ScriptBase
    {
        public override string GetScript()
        {
            return @"!function(){""use strict"";function e(e,...t){const{DomHelpers:i}=window.Skclusive.Script;return i[e].apply(null,t)}class t{static construct(i,n){const l=function(...t){return e(""generateId"",...t)}(),r=t.callback(l);return t.cache[l]={id:l,list:i,textCriteria:{keys:[],repeating:!0,previousKeyMatched:!0,lastTime:null},disableListWrap:n,callback:r},t.initialize(l),l}static initialize(e){const i=t.cache[e];i&&document.addEventListener(""keydown"",i.callback)}static callback(i){return n=>{const l=t.cache[i],{list:c,disableListWrap:u,textCriteria:d}=l,f=n.key,p=function(...t){return e(""ownerDocument"",...t)}(c).activeElement;if(""ArrowDown""===f)n.preventDefault(),o(i,c,p,u,r);else if(""ArrowUp""===f)n.preventDefault(),o(i,c,p,u,s);else if(""Home""===f)n.preventDefault(),o(i,c,null,u,r);else if(""End""===f)n.preventDefault(),o(i,c,null,u,s);else if(1===f.length){const e=d,t=f.toLowerCase(),l=performance.now();e.keys.length>0&&(l-e.lastTime>500?(e.keys=[],e.repeating=!0,e.previousKeyMatched=!0):e.repeating&&t!==e.keys[0]&&(e.repeating=!1)),e.lastTime=l,e.keys.push(t);const s=p&&!e.repeating&&a(p,e);e.previousKeyMatched&&(s||o(i,c,p,!1,r,e))?n.preventDefault():e.previousKeyMatched=!1}}}static dispose(e){const i=t.cache[e];i&&i.callback&&document.removeEventListener(""keydown"",i.callback),delete t.cache[e]}}var i,n,l;function r(e,t,i){return e===t?e.firstElementChild:t&&t.nextElementSibling?t.nextElementSibling:i?null:e.firstElementChild}function s(e,t,i){return e===t?i?e.firstElementChild:e.lastElementChild:t&&t.previousElementSibling?t.previousElementSibling:i?null:e.lastElementChild}function a(e,t){if(void 0===t)return!0;let i=e.innerText;return void 0===i&&(i=e.textContent),void 0!==i&&(i=i.trim().toLowerCase(),0!==i.length&&(t.repeating?i[0]===t.keys[0]:0===i.indexOf(t.keys.join(""""))))}function c(i,n){const l=t.cache[i],{list:r,lastFocused:s=r.querySelector("".ListItem-FocusVisible"")}=l;n.focus(),function(...t){e(""addClasses"",...t)}(n,[""ListItem-FocusVisible""]),s&&function(...t){e(""removeClasses"",...t)}(s,[""ListItem-FocusVisible""]),l.lastFocused=n}function o(e,t,i,n,l,r){let s=!1,o=l(t,i,!!i&&n);for(;o;){if(o===t.firstElementChild){if(s)return!1;s=!0}if(o.hasAttribute(""tabindex"")&&!o.disabled&&""true""!==o.getAttribute(""aria-disabled"")&&a(o,r))return c(e,o),!0;o=l(t,o,n)}return!1}l={},(n=""cache"")in(i=t)?Object.defineProperty(i,n,{value:l,enumerable:!0,configurable:!0,writable:!0}):i[n]=l,window.Skclusive={...window.Skclusive,Material:{...(window.Skclusive||{}).Material,Menu:{MenuListHelper:t}}}}();";
        }
    }
}
